### ISSUE TITLE
新docker镜像报错 type object 'CronTrigger' has no attribute 'from_crontab'

### ISSUE THREAD

**Issue by Silentely** [luminoleon/epicgames-claimer#114]
[2022-01-02 20:07:02  INFO] Claimer started
[2022-01-02 20:07:02  INFO] start schedule use crontab: 30 01
 * * *
[2022-01-02 20:07:04  INFO] Bark Response HTTP Status Code: 2
00
[2022-01-02 20:07:04  INFO] Bark Response HTTP Response Body:
 b'{"code":200,"message":"success","timestamp":1641125224}'
[2022-01-02 20:07:55  INFO] All available free games are alre
ady in your library
Traceback (most recent call last):
  File "main.py", line 123, in <module>
    main()
  File "main.py", line 118, in main
    run_once() if args.once else run_forever()
  File "main.py", line 109, in run_forever
    cron_schedule.add_job(run_once, CronTrigger.from_crontab(
cron_expression))
AttributeError: type object 'CronTrigger' has no attribute 'from_crontab'

**Comment by dingtang001** [comment]
我这里也是。

**Comment by dingtang001** [comment]
<html>
<body>
<h2 style="text-align: center; color: rgb(0, 0, 0); font-family: &quot;Lucida Console&quot;, Consola, Monaco, monospace, &quot;Courier New&quot;, Courier, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">luminoleon-epicgames-claimer1</h2>

date | stream | content
-- | -- | --
2022-01-02 16:06:11 | stdout | AttributeError: type object 'CronTrigger' has no attribute 'from_crontab'
2022-01-02 16:06:11 | stdout | cron_schedule.add_job(run_once, CronTrigger.from_crontab(cron_expression))
2022-01-02 16:06:11 | stdout | File "main.py", line 109, in run_forever
2022-01-02 16:06:11 | stdout | run_once() if args.once else run_forever()
2022-01-02 16:06:11 | stdout | File "main.py", line 118, in main
2022-01-02 16:06:11 | stdout | main()
2022-01-02 16:06:11 | stdout | File "main.py", line 123, in <module>
2022-01-02 16:06:11 | stdout | Traceback (most recent call last):
2022-01-02 16:06:11 | stdout | [2022-01-03 00:06:11  INFO] All available free games are already in your library
2022-01-02 16:04:49 | stdout | [2022-01-03 00:04:49  INFO] start schedule use crontab: 04 00 * * *
2022-01-02 16:04:49 | stdout | [2022-01-03 00:04:49  INFO] Claimer started
2022-01-02 15:59:42 | stdout | AttributeError: type object 'CronTrigger' has no attribute 'from_crontab'
2022-01-02 15:59:42 | stdout | cron_schedule.add_job(run_once, CronTrigger.from_crontab(cron_expression))
2022-01-02 15:59:42 | stdout | File "main.py", line 109, in run_forever
2022-01-02 15:59:42 | stdout | run_once() if args.once else run_forever()
2022-01-02 15:59:42 | stdout | File "main.py", line 118, in main
2022-01-02 15:59:42 | stdout | main()
2022-01-02 15:59:42 | stdout | File "main.py", line 123, in <module>
2022-01-02 15:59:42 | stdout | Traceback (most recent call last):
2022-01-02 15:59:42 | stdout | [2022-01-02 23:59:42  INFO] All available free games are already in your library
2022-01-02 15:57:56 | stdout | [2022-01-02 23:57:56  INFO] start schedule use crontab: 57 23 * * *
2022-01-02 15:57:56 | stdout | [2022-01-02 23:57:56  INFO] Claimer started


</body>
</html>
