### ISSUE TITLE
登陆超时有办法解决么

### ISSUE THREAD

**Issue by RichardsATcn** [luminoleon/epicgames-claimer#4]
大佬 登陆超时啊
[Fri Sep 17 16:41:01 2021] Warning: Waiting for selector "#sign-in[tabindex='0']" failed: timeout 120000ms exceeds.

**Comment by luminoleon** [comment]
如果不是最新版本，先用最新版本试一试。
如果是最新版本，那大概是加载太慢了（Epic服务器的问题），多试几次可能会好。

**Comment by fantuanda** [comment]
大佬，为啥我挂在云函数上面不行呢，测试都跑不起来，本地用pyth3.9提示Traceback (most recent call last):
  File "G:\Desktop\EpicGames-Claimer-v1.5.1-Python\epicgames-claimer\main.py", line 5, in <module>
    import update_check
ModuleNotFoundError: No module named 'update_check'

**Comment by luminoleon** [comment]
> 大佬，为啥我挂在云函数上面不行呢，测试都跑不起来，本地用pyth3.9提示Traceback (most recent call last):
> File "G:\Desktop\EpicGames-Claimer-v1.5.1-Python\epicgames-claimer\main.py", line 5, in
> import update_check
> ModuleNotFoundError: No module named 'update_check'

你需要把Python模块（requirements.txt里面）和Linux版Chromium一并打包进去。云函数我试过了，Chromium运行不正常，所以没办法使用。

另外我推荐你可以在云函数上使用其他更好的脚本，体积小，不依赖浏览器。我这个也就使用起来比较简单，其他方面不太行。<https://github.com/Revadike/epicgames-freebies-claimer>
<https://github.com/claabs/epicgames-freegames-node>

**Comment by Booy1x** [comment]
> 大佬 登陆超时啊
> [Fri Sep 17 16:41:01 2021] Warning: Waiting for selector "#sign-in[tabindex='0']" failed: timeout 120000ms exceeds.

你可以试试hosts
104.16.168.131 hcaptcha.com
104.16.168.131 newassets.hcaptcha.com
104.16.168.131 imgs.hcaptcha.com
