### ISSUE TITLE
pyppeteer.errors.NetworkError: Protocol error Page.enable: Target closed.

### ISSUE THREAD

**Issue by aprz512** [luminoleon/epicgames-claimer#41]
报了网络错误，但是是有网的...
[2021-11-22 14:30:04  INFO] Claimer started
Traceback (most recent call last):
  File "epicgames_claimer.py", line 950, in <module>
    main()
  File "epicgames_claimer.py", line 922, in main
    claimer = EpicgamesClaimer(args.data_dir, headless=not args.no_headless, chromium_path=args.chromium_path, claimer_notifications=claimer_notifications, timeout=args.debug_timeout, debug=args.debug)
  File "epicgames_claimer.py", line 287, in __init__
    self.open_browser()
  File "epicgames_claimer.py", line 821, in open_browser
    return self._loop.run_until_complete(self._open_browser_async())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "epicgames_claimer.py", line 339, in _open_browser_async
    self.page = (await self.browser.pages())[0]
  File "/home/aprz512/.local/lib/python3.8/site-packages/pyppeteer/browser.py", line 242, in pages
    pages.extend(await context.pages())
  File "/home/aprz512/.local/lib/python3.8/site-packages/pyppeteer/browser.py", line 330, in pages
    page = await target.page()
  File "/home/aprz512/.local/lib/python3.8/site-packages/pyppeteer/target.py", line 64, in page
    new_page = await Page.create(
  File "/home/aprz512/.local/lib/python3.8/site-packages/pyppeteer/page.py", line 92, in create
    await client.send('Page.enable'),
pyppeteer.errors.NetworkError: Protocol error Page.enable: Target closed.

**Comment by luminoleon** [comment]
我觉得有两种可能：有些Python模块不兼容，或者浏览器版本不兼容。可以试一下重新安装pyppeteer，或者使用通过包管理器安装的chromium

**Comment by aprz512** [comment]
恩， 我试一下看看，我是在windows下的子系统ubuntu上运行的。On Nov 22, 2021 23:35, luminoleon ***@***.***> wrote:

我觉得有两种可能：有些Python模块不兼容，或者浏览器版本不兼容。可以试一下重新安装pyppeteer，或者使用通过包管理器安装的chromium
