### ISSUE TITLE
通过cookies登录，用参数--cookies指定cookies文件路径

### ISSUE THREAD

**Issue by wmjlxl** [luminoleon/epicgames-claimer#47]
最新的 1.66 可以设置 cookies

请问这个在 docker 下的话，如何设置呢？

Container Path: ?

thanks。

**Comment by wmjlxl** [comment]
明白了谢谢，刚设置好。
但是还是出现这个错误：


[33m[2021-11-29 21:50:43 WARN] Waiting for selector "#purchase-app button[class*=confirm]:not([disabled])" failed: timeout 180000ms exceeds.[0m

[33m[2021-11-29 21:53:46 WARN] Waiting for selector "#purchase-app button[class*=confirm]:not([disabled])" failed: timeout 180000ms exceeds.[0m

[31m[2021-11-29 21:56:49 ERROR] Failed to claim one item: Waiting for selector "#purchase-app button[class*=confirm]:not([disabled])" failed: timeout 180000ms exceeds.[0m

**Comment by luoyuu77** [comment]
> 

如何获取cookies啊
root@5d8abd335fef:/# python3.6 get_cookies.py 
Traceback (most recent call last):
  File "get_cookies.py", line 27, in <module>
    asyncio.run(save_cookies("cookies.json"))
AttributeError: module 'asyncio' has no attribute 'run'
root@5d8abd335fef:/#

**Comment by wmjlxl** [comment]
> > 
> 
> 如何获取cookies啊 root@5d8abd335fef:/# python3.6 get_cookies.py Traceback (most recent call last): File "get_cookies.py", line 27, in asyncio.run(save_cookies("cookies.json")) AttributeError: module 'asyncio' has no attribute 'run' root@5d8abd335fef:/#

我是直接用 .exe 在 win 下获取
