### ISSUE TITLE
pyppeteer.errors.BrowserError: Browser closed unexpectedly

### ISSUE THREAD

**Issue by Clancyli** [luminoleon/epicgames-claimer#56]
大佬大佬，试了好多次，不是timeout就是这个错误，请问有办法解决嘛？
系统 Debian10

docker run -it luminoleon/epicgames-claimer:1.6.7 -u *@gmail.com -p *

[2021-12-11 08:39:48  INFO] Claimer started
Traceback (most recent call last):
  File "epicgames_claimer.py", line 1054, in <module>
    main()
  File "epicgames_claimer.py", line 1025, in main
    cookies=args.cookies
  File "epicgames_claimer.py", line 309, in __init__
    self.open_browser()
  File "epicgames_claimer.py", line 874, in open_browser
    return self._loop.run_until_complete(self._open_browser_async())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "epicgames_claimer.py", line 342, in _open_browser_async
    executablePath=self.chromium_path,
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

**Comment by Clancyli** [comment]
docker run -it luminoleon/epicgames-claimer:1.6.7 -u *@gmail.com -p * -c '/usr/lib/chromium/
会出现FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/chromium/': '/usr/lib/chromium/'

**Comment by Clancyli** [comment]
> docker run -it luminoleon/epicgames-claimer:1.6.7 -u *@gmail.com -p * -c '/usr/lib/chromium/ 会出现FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/chromium/': '/usr/lib/chromium/'

[2021-12-11 09:30:16  INFO] Claimer started
Traceback (most recent call last):
  File "epicgames_claimer.py", line 1054, in <module>
    main()
  File "epicgames_claimer.py", line 1025, in main
    cookies=args.cookies
  File "epicgames_claimer.py", line 309, in __init__
    self.open_browser()
  File "epicgames_claimer.py", line 874, in open_browser
    return self._loop.run_until_complete(self._open_browser_async())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "epicgames_claimer.py", line 342, in _open_browser_async
    executablePath=self.chromium_path,
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py", line 149, in launch
    self.cmd, **options, )
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/chromium/chromium': '/usr/lib/chromium/'

**Comment by luminoleon** [comment]
这个我也不知道是什么情况了。

可以试一下1.6.7-alpine这个镜像，或者直接用Python脚本加参数-c /usr/lib/chromium试一试。

**Comment by 2375399351** [comment]
一样这个问题

**Comment by kivid** [comment]
复现了这个问题，大抵arm64产生的对照过x86，环境如下
` chromium-94.0.4606.81-1.el8.aarch64  鲲鹏arm64` 
![image](https://user-images.githubusercontent.com/44400198/146664623-b91a5031-44db-4ff7-81a3-f0c3b658a759.png)

**Comment by kivid** [comment]
> 复现了这个问题，大抵arm64产生的对照过x86，环境如下 ` chromium-94.0.4606.81-1.el8.aarch64 鲲鹏arm64` ![image](https://user-images.githubusercontent.com/44400198/146664623-b91a5031-44db-4ff7-81a3-f0c3b658a759.png)

找了一圈没找到arm64的Google Chrome替代，官方也没给，这个得编译了？

**Comment by liubowwen** [comment]
安装一下需要的环境就可以了
yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 -y

**Comment by kivid** [comment]
> 安装一下需要的环境就可以了 yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 -y

这arm64能装吗
