### ISSUE TITLE
报错云函数

### ISSUE THREAD

**Issue by live2364li** [luminoleon/epicgames-claimer#76]
START RequestId: 6750a7b8-d955-4dd4-99b3-a52ddbe2ac2c

Init Report RequestId: 6750a7b8-d955-4dd4-99b3-a52ddbe2ac2c Coldstart: 838ms (PullCode: 10ms InitRuntime: 236ms InitFunction: 592ms) Memory: 1024MB MemUsage: 19.79MB

ERROR RequestId: 6750a7b8-d955-4dd4-99b3-a52ddbe2ac2c Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/epicgames_claimer.py", line 19, in <module>     import schedule ModuleNotFoundError: No module named 'schedule'", "statusCode": 443}

END RequestId: 6750a7b8-d955-4dd4-99b3-a52ddbe2ac2c

Report RequestId: 6750a7b8-d955-4dd4-99b3-a52ddbe2ac2c Duration: 0ms Memory: 1024MB MemUsage: 19.79MB

START RequestId:6750a7b8-d955-4dd4-99b3-a52ddbe2ac2c

ERROR RequestId:6750a7b8-d955-4dd4-99b3-a52ddbe2ac2c Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/epicgames_claimer.py\", line 19, in \u003cmodule\u003e\n    import schedule\nModuleNotFoundError: No module named 'schedule'","statusCode":443}

END RequestId:6750a7b8-d955-4dd4-99b3-a52ddbe2ac2c

Report RequestId:6750a7b8-d955-4dd4-99b3-a52ddbe2ac2c Duration:0ms Memory:1024MB MemUsage:0.000000MB

**Comment by live2364li** [comment]
麻烦作者看一下

**Comment by luminoleon** [comment]
日志里说schedule这个模块没有装，检查一下前面的步骤是不是都正确执行了

**Comment by live2364li** [comment]
START RequestId: 0bb8889d-88e9-4c31-84ab-d5c496e3ccc2

Init Report RequestId: 0bb8889d-88e9-4c31-84ab-d5c496e3ccc2 Coldstart: 818ms (PullCode: 9ms InitRuntime: 229ms InitFunction: 580ms) Memory: 1024MB MemUsage: 19.81MB

ERROR RequestId: 0bb8889d-88e9-4c31-84ab-d5c496e3ccc2 Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/epicgames_claimer.py", line 19, in <module>     import schedule ModuleNotFoundError: No module named 'schedule'", "statusCode": 443}

END RequestId: 0bb8889d-88e9-4c31-84ab-d5c496e3ccc2

Report RequestId: 0bb8889d-88e9-4c31-84ab-d5c496e3ccc2 Duration: 0ms Memory: 1024MB MemUsage: 19.81MB

START RequestId:0bb8889d-88e9-4c31-84ab-d5c496e3ccc2

ERROR RequestId:0bb8889d-88e9-4c31-84ab-d5c496e3ccc2 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/epicgames_claimer.py\", line 19, in \u003cmodule\u003e\n    import schedule\nModuleNotFoundError: No module named 'schedule'","statusCode":443}

END RequestId:0bb8889d-88e9-4c31-84ab-d5c496e3ccc2

Report RequestId:0bb8889d-88e9-4c31-84ab-d5c496e3ccc2 Duration:0ms Memory:1024MB MemUsage:0.000000MB

**Comment by live2364li** [comment]
还是报错

**Comment by live2364li** [comment]
START RequestId:373f7068-c20e-48e1-a98e-25c9209be6df

ERROR RequestId:373f7068-c20e-48e1-a98e-25c9209be6df Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/epicgames_claimer.py\", line 1076, in main_handler\n    claimed_item_titles = main(args, raise_error=True)\n  File \"/var/user/epicgames_claimer.py\", line 1053, in main\n    push_when_owned_all=args.push_when_owned_all\n  File \"/var/user/epicgames_claimer.py\", line 316, in __init__\n    self.open_browser()\n  File \"/var/user/epicgames_claimer.py\", line 900, in open_browser\n    return self._loop.run_until_complete(self._open_browser_async())\n  File \"/var/lang/python3/lib/python3.6/asyncio/base_events.py\", line 466, in run_until_complete\n    return future.result()\n  File \"/var/user/epicgames_claimer.py\", line 349, in _open_browser_async\n    executablePath=self.chromium_path,\n  File \"/var/user/pyppeteer/launcher.py\", line 307, in launch\n    return await Launcher(options, **kwargs).launch()\n  File \"/var/user/pyppeteer/launcher.py\", line 149, in launch\n    self.cmd, **options, )\n  File \"/var/lang/python3/lib/python3.6/subprocess.py\", line 707, in __init__\n    restore_signals, start_new_session)\n  File \"/var/lang/python3/lib/python3.6/subprocess.py\", line 1326, in _execute_child\n    raise child_exception_type(errno_num, err_msg)\nFileNotFoundError: [Errno 2] No such file or directory: '/tmp/chrome-linux/chrome'","statusCode":430}

END RequestId:373f7068-c20e-48e1-a98e-25c9209be6df

Report RequestId:373f7068-c20e-48e1-a98e-25c9209be6df Duration:20ms Memory:1024MB MemUsage:23.285156MB

**Comment by live2364li** [comment]
成功了，谢谢云函数更新频繁吗

**Comment by Cairl** [comment]
> 日志里说schedule这个模块没有装，检查一下前面的步骤是不是都正确执行了

我在部署云函数时也常常会这样，原因是要多src下多执行几次
`pip3 install -r requirements.txt -t .
mv bin/pyppeteer-install .
./pyppeteer-install
cp -r /root/.local/share/pyppeteer/local-chromium/*/chrome-linux .`
试了几次发现输入一次是肯定不行的，至少2-3次，不知道是怎么回事

**Comment by live2364li** [comment]
谢谢，好兄弟
